<?xml version="1.0" encoding="UTF-8"?>
<!-- This file sets the directories used by the project files (.csproj) -->
<Project>
  <PropertyGroup>
    <!-- this registers the property `RootDirectory` as the top level dir -->
    <RootDirectory>$(MSBuildThisFileDirectory.TrimEnd('/').TrimEnd('\'))</RootDirectory>
    <!-- Project directories -->
    <SourceDirectory>$(RootDirectory)\src</SourceDirectory>
    <StageDirectory>$(RootDirectory)\stage</StageDirectory>
    <ArtifactDirectory>$(RootDirectory)\out</ArtifactDirectory>
    <BaseOutputPath>$(ArtifactDirectory)</BaseOutputPath>
    <BaseIntermediateOutputPath>$(ArtifactDirectory)\obj\$(MSBuildProjectName)</BaseIntermediateOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <!-- Everything will be built in the out directory, but the final product will be in
      stage -->
    <OutDir>$(StageDirectory)\$(MSBuildProjectName)</OutDir>
  </PropertyGroup>
  <!-- Code analysis -->
  <PropertyGroup>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>
</Project>
