//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("ASI")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("2025 Timothy R. Aldrich. All rights reserved.")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Achieve mind-like-water")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("0.1.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.1.0")]
[assembly: System.Reflection.AssemblyProductAttribute("Water")]
[assembly: System.Reflection.AssemblyTitleAttribute("Water")]
[assembly: System.Reflection.AssemblyVersionAttribute("0.1.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

